# Data Preprocessing Ex_1

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
# importing dataset
data = pd.read_csv('Data.csv')

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
States       10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [36]:
data

States   Age   Salary Purchased
0       Texas  44.0  72000.0        No
1     Florida  27.0  48000.0       Yes
2  California  30.0  54000.0        No
3       Texas  38.0  61000.0        No
4  California   NaN  65000.0       Yes
5       Texas  35.0  58000.0       Yes
6  California  40.0      NaN        No
7       Texas  48.0  79000.0       Yes
8     Florida  50.0  83000.0        No
9       Texas  37.0  67000.0       Yes

In [37]:
type(data)

pandas.core.frame.DataFrame

In [38]:
x = data.iloc[:,:3]
x

States   Age   Salary
0       Texas  44.0  72000.0
1     Florida  27.0  48000.0
2  California  30.0  54000.0
3       Texas  38.0  61000.0
4  California   NaN  65000.0
5       Texas  35.0  58000.0
6  California  40.0      NaN
7       Texas  48.0  79000.0
8     Florida  50.0  83000.0
9       Texas  37.0  67000.0

In [39]:
x = data.iloc[:,:3].values
x

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', nan, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, nan],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

In [40]:
y = data.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [41]:
# handling the missing data
# There are many strategies to handle missing data, we can take the average or median or mean of the column. Here we will take the median value.
from sklearn.preprocessing import Imputer

In [42]:
imputer = Imputer(missing_values= 'NaN', strategy='mean' , axis=0)
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
x

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', 38.77777777777778, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, 65222.22222222222],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

In [43]:
#Encoding the categorical variables
from sklearn.preprocessing import LabelEncoder
labelEncoder_x =  LabelEncoder()
x[:,0] = labelEncoder_x.fit_transform(x[:, 0])
labelEncoder_y = LabelEncoder()
y = labelEncoder_y.fit_transform(y)

In [21]:
x

array([[2, 44.0, 72000.0],
       [1, 27.0, 48000.0],
       [0, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [0, 38.77777777777778, 65000.0],
       [2, 35.0, 58000.0],
       [0, 40.0, 65222.22222222222],
       [2, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [2, 37.0, 67000.0]], dtype=object)

In [44]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [45]:
#Creating dummy variables for the encoded categorical values
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\avinash\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [52]:
x                            # Here columns 0, 1, and 2 represent dummy variables for the three categorical values.

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.87777778e+01,
        6.50000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.52222222e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [53]:
# Splitting the dataset: Now, we need to split the dataset into training and test dataset. 
#The training dataset is used to train the machine learning model and test dataset is to test the model
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2,random_state = 0)

In [54]:
x_train

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.87777778e+01,
        6.50000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.52222222e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [55]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [56]:
x_test

array([[1.0e+00, 0.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

In [57]:
y_test

array([0, 0])

In [62]:
x

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.87777778e+01,
        6.50000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.52222222e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])